# Generated by Django 5.0.4 on 2024-12-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
